export const DUMMY_USERS = [
  {
    id: "cust_001",
    name: "Ama Serwaa",
    email: "ama.serwaa@gmail.com",
    role: "customer",
    phone: "0244123456",
    isWhatsApp: true,
    address: "AK-123-4567", // Digital Address
    location: "Nhyiaeso, Kumasi",
    joinDate: "2024-01-15",
    avatar: "https://api.dicebear.com",
    totalJobsPosted: 12,
    bio: "Homeowner looking for reliable maintenance services in the Nhyiaeso area.",
  },
  {
    id: "art_001",
    name: "Samuel Osei",
    businessName: "Samuel's Pro Plumbing",
    email: "samuel.plumb@yahoo.com",
    role: "artisan",
    category: "Plumbing",
    phone: "0557890123",
    isWhatsApp: true,
    address: "AK-044-9021",
    location: "Adum, Kumasi",
    rating: 4.9,
    reviewCount: 128,
    isVerified: true,
    yearsExperience: 8,
    avatar: "https://api.dicebear.com",
    bio: "Certified master plumber specializing in industrial piping and domestic leak repairs.",
    skills: ["Pipe Fitting", "Tiling", "Water Heater Installation"],
    baseRate: "GH₵ 100/hr",
  },
  {
    id: "art_002",
    name: "Kwame Boateng",
    businessName: "Elite Electricals",
    email: "elite.electrics@icloud.com",
    role: "artisan",
    category: "Electrical",
    phone: "0201112223",
    isWhatsApp: true,
    address: "AK-992-1002",
    location: "Ahodwo, Kumasi",
    rating: 4.7,
    reviewCount: 94,
    isVerified: true,
    yearsExperience: 5,
    avatar: "https://api.dicebear.com",
    bio: "Expert in smart home wiring, CCTV installation, and solar panel maintenance.",
    skills: ["Solar Wiring", "CCTV", "Fault Finding", "Air Conditioning"],
    baseRate: "GH₵ 120/hr",
  },
  {
    id: "art_003",
    name: "Isaac Appiah",
    businessName: "The Wood Wizard",
    email: "isaac.wood@gmail.com",
    role: "artisan",
    category: "Carpentry",
    phone: "0243114455",
    isWhatsApp: false,
    address: "AK-221-5544",
    location: "Asokwa, Kumasi",
    rating: 4.8,
    reviewCount: 56,
    isVerified: false,
    yearsExperience: 12,
    avatar: "https://api.dicebear.com",
    bio: "Bespoke furniture maker and roof framing expert.",
    skills: ["Roofing", "Furniture Design", "Cabinetry"],
    baseRate: "GH₵ 150/hr",
  },
];
